version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Docker Hub..."
      - |
        if [[ -z "$DOCKER_HUB_USERNAME" || -z "$DOCKER_HUB_PASSWORD" ]]; then 
          echo "Error: DOCKER_HUB credentials not set" 
          exit 1
        fi
      - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
      - export IMAGE_TAG=$(date +%Y%m%d%H%M%S)
      - echo "Image tag: $IMAGE_TAG"
      - echo "Setting up AWS credentials..."
      - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
      - echo "AWS credentials configured."

  build:
    commands:
      - echo "Building Docker image..."
      - |
        docker build \
          --build-arg AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
          --build-arg AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
          --build-arg AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION \
          -t satya368/healthcare_system:$IMAGE_TAG .
      - echo "Pushing Docker image to Docker Hub..."
      - docker push satya368/healthcare_system:$IMAGE_TAG

  post_build:
    commands:
      - echo "Writing Dockerrun.aws.json file..."
      - |
        echo '{
          "AWSEBDockerrunVersion": "1",
          "Image": {
            "Name": "satya368/healthcare_system:'"$IMAGE_TAG"'",
            "Update": "true"
          },
          "Ports": [
            {
              "ContainerPort": 80
            }
          ],
          "Environment": [
            {
              "Name": "AWS_ACCESS_KEY_ID",
              "Value": "'"$AWS_ACCESS_KEY_ID"'"
            },
            {
              "Name": "AWS_SECRET_ACCESS_KEY",
              "Value": "'"$AWS_SECRET_ACCESS_KEY"'"
            },
            {
              "Name": "AWS_DEFAULT_REGION",
              "Value": "'"$AWS_DEFAULT_REGION"'"
            }
          ]
        }' > Dockerrun.aws.json
      - echo "Build completed on $(date)"

artifacts:
  files:
    - Dockerrun.aws.json
